version: "3.9"
services:
    db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_airbnb
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_TCP_PORT: 3306
      container_name: mysql
      ports:
          - 3306:3306
      volumes:
          - db-airbnb:/var/lib/mysql

    adminer:
      image: adminer:latest
      environment:
        ADMINER_DEFAULT_SERVER: db
      ports:
        - 8080:8080

    airbnb:
      build:
        context: .
        dockerfile: Dockerfile
      command: 'python manage.py runserver 0.0.0.0:8000'
      ports:
        - 8000:8000
      expose:
        - 8000
      depends_on:
        - db

volumes:
  db-airbnb: